# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgpt < Formula
  desc "A simple command line tool for working with LLMs."
  homepage "https://github.com/tmc/cgpt"
  version "0.4.4"

  on_macos do
    on_intel do
      url "https://github.com/tmc/cgpt/releases/download/v0.4.4/cgpt_Darwin_x86_64.tar.gz"
      sha256 "1f1c2bf43e06cd68362b432e21f5808653ab02c52af148f67d23fde19438705a"

      def install
        bin.install "cgpt"
      end
    end
    on_arm do
      url "https://github.com/tmc/cgpt/releases/download/v0.4.4/cgpt_Darwin_arm64.tar.gz"
      sha256 "43c103126589d9de6566d9028ff82922125dec6e8f89d4006774bca9cd12c8e7"

      def install
        bin.install "cgpt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmc/cgpt/releases/download/v0.4.4/cgpt_Linux_x86_64.tar.gz"
        sha256 "317f10aec951293681a07d100120fa54f2b8aff08f835d40e2228f334e020d88"

        def install
          bin.install "cgpt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmc/cgpt/releases/download/v0.4.4/cgpt_Linux_arm64.tar.gz"
        sha256 "2c53ac26b0a5623e4345956de16ce9280e352544a1e31ee2799d3c64d8239c35"

        def install
          bin.install "cgpt"
        end
      end
    end
  end

  head do
    url "https://github.com/tmc/cgpt.git"
    depends_on "pkg-config" => :build
  end
end
